services:
  # Config Servers
  cfgsvr1:
    image: mongo:5.0
    container_name: cfgsvr1
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    volumes:
      - cfgsvr1:/data/db
    networks:
      - mongocluster

  cfgsvr2:
    image: mongo:5.0
    container_name: cfgsvr2
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    volumes:
      - cfgsvr2:/data/db
    networks:
      - mongocluster

  cfgsvr3:
    image: mongo:5.0
    container_name: cfgsvr3
    command: mongod --configsvr --replSet cfgrs --port 27017 --dbpath /data/db
    volumes:
      - cfgsvr3:/data/db
    networks:
      - mongocluster

  # Shard 1 Replica Set
  shard1svr1:
    image: mongo:5.0
    container_name: shard1svr1
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    volumes:
      - shard1svr1:/data/db
    networks:
      - mongocluster

  shard1svr2:
    image: mongo:5.0
    container_name: shard1svr2
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    volumes:
      - shard1svr2:/data/db
    networks:
      - mongocluster

  shard1svr3:
    image: mongo:5.0
    container_name: shard1svr3
    command: mongod --shardsvr --replSet shard1rs --port 27017 --dbpath /data/db
    volumes:
      - shard1svr3:/data/db
    networks:
      - mongocluster

  # Shard 2 Replica Set
  shard2svr1:
    image: mongo:5.0
    container_name: shard2svr1
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    volumes:
      - shard2svr1:/data/db
    networks:
      - mongocluster

  shard2svr2:
    image: mongo:5.0
    container_name: shard2svr2
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    volumes:
      - shard2svr2:/data/db
    networks:
      - mongocluster

  shard2svr3:
    image: mongo:5.0
    container_name: shard2svr3
    command: mongod --shardsvr --replSet shard2rs --port 27017 --dbpath /data/db
    volumes:
      - shard2svr3:/data/db
    networks:
      - mongocluster

  # Shard 3 Replica Set
  shard3svr1:
    image: mongo:5.0
    container_name: shard3svr1
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db
    volumes:
      - shard3svr1:/data/db
    networks:
      - mongocluster

  shard3svr2:
    image: mongo:5.0
    container_name: shard3svr2
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db
    volumes:
      - shard3svr2:/data/db
    networks:
      - mongocluster

  shard3svr3:
    image: mongo:5.0
    container_name: shard3svr3
    command: mongod --shardsvr --replSet shard3rs --port 27017 --dbpath /data/db
    volumes:
      - shard3svr3:/data/db
    networks:
      - mongocluster

  # Routers
  router1:
    image: mongo:5.0
    container_name: router1
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27117:27017
    networks:
      - mongocluster
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3

  router2:
    image: mongo:5.0
    container_name: router2
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27217:27017
    networks:
      - mongocluster
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3

  router3:
    image: mongo:5.0
    container_name: router3
    command: mongos --configdb cfgrs/cfgsvr1:27017,cfgsvr2:27017,cfgsvr3:27017 --bind_ip 0.0.0.0 --port 27017
    ports:
      - 27317:27017
    networks:
      - mongocluster
    depends_on:
      - cfgsvr1
      - cfgsvr2
      - cfgsvr3

networks:
  mongocluster:
    driver: bridge

volumes:
  cfgsvr1:
  cfgsvr2:
  cfgsvr3:
  shard1svr1:
  shard1svr2:
  shard1svr3:
  shard2svr1:
  shard2svr2:
  shard2svr3:
  shard3svr1:
  shard3svr2:
  shard3svr3: